#!/bin/bash
SZ=$(blockdev --getsize /dev/mapper/altroot)
dmsetup suspend top
echo 0 $SZ snapshot-merge /dev/mapper/altroot /dev/loop0 p 8 | dmsetup --checks -v create mergeomatic &
dmsetup status
while read aLine ; do
	dmsetup status
	if [ "$aLine" = "x" ] ; then
		dmsetup resume top
		dmsetup remove mergeomatic
		exit
	fi
done
